# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 		
	config.vm.define :servidor do |servidor|
 		servidor.vm.box = "jharlingrodriguez/my_new_box_servidor"
		servidor.vm.box_version = "0.0.4"
 		servidor.vm.network :private_network, ip: "192.168.50.3"
 		servidor.vm.hostname = "servidor"
		servidor.vm.boot_timeout = 600
 	end
 	config.vm.define :cliente do |cliente|
 		cliente.vm.box = "jharlingrodriguez/my_new_box_servidor"
		cliente.vm.box_version = "0.0.2"
 		cliente.vm.network :private_network, ip: "192.168.50.2"
 		cliente.vm.hostname = "cliente"
		cliente.vm.boot_timeout = 600
 	end
end